chore: optimize metrics creation and add documentation
orange-cloudavenue/kube-image-updater pull request #66
Opened 2024-10-20 10:07 UTC by azrod

2024-10-20 10:28 UTC, azrod commented
Ignore commit pre-commit ci

2024-10-21 13:01 UTC, dmicheneau requested changes

2024-10-21 13:01 UTC, dmicheneau commented on internal/metrics/admission-controller.go
> +		Total         prometheus.Counter `help:"The total number of action performed."`
is not an 'action' is a number of time 'admission controller' is call

2024-10-21 15:19 UTC, dmicheneau requested changes

2024-10-21 15:19 UTC, dmicheneau commented on cmd/admission-controller/webhook.go
> +		metrics.AdmissionController().PatchErrTotal.Inc()
change it by PatchErrorTotal

2024-10-21 15:19 UTC, dmicheneau commented on internal/metrics/admission-controller.go
> +		PatchErrTotal     prometheus.Counter `help:"The total number of patch action performed with error."`
Suggest to uniform: PatchErrorTotal

2024-10-21 15:19 UTC, dmicheneau commented on internal/metrics/events.go
> +	if eventsMetrics.TriggerdTotal == nil {
```suggestion
	if eventsMetrics.TriggeredTotal == nil {
```

2024-10-21 15:19 UTC, dmicheneau commented on internal/metrics/events.go
> +		TriggerdTotal      prometheus.Counter `help:"The total number of events triggered."`
```suggestion
		TriggeredTotal      prometheus.Counter `help:"The total number of events triggered."`
```

2024-10-21 15:19 UTC, dmicheneau commented on test/metrics/metrics_test.go
> +				if err := testutil.CollectAndCompare(tt.c, strings.NewReader(tt.data+tt.nameMetric+tt.value), tt.nameMetric); err != nil {
```suggestion
				if err := testutil.CollectAndCompare(counter, strings.NewReader(tt.data+tt.nameMetric+tt.value), tt.nameMetric); err != nil {
```
In logic, we need to compare the object that we have increment before.

2024-10-22 07:54 UTC, dmicheneau approved these changes

2024-10-22 07:59 UTC, merged